version: '3'

services:
  mediathekview:
    build: .
    container_name: mediathekview
    ports:
      - "5800:5800"
    volumes:
      - "$HOME/mediathekview/config:/config:rw"
      - "$HOME/mediathekview/output:/output:rw"
    environment:
       - "USER_ID=1000"
       - "GROUP_ID=1000"
